### ISSUE TITLE
Icon variables for sass

### ISSUE THREAD

**Issue by mmuellerMG** [HaoyCn/iconfont-plugin-webpack#6]
Hi guys,

is it possible to create a global variable of each icon? Let's say I have an icon named twitter.svg, I need a var with the prefix, that has the unicode stored.

For example (twitter.svg with $icon-prefix: 'foo'; ):

`$foo-twitter = "\ea49";`

so I can use in another scss-file:

`	.bar{
		&::after {
			content: $foo-twitter;
		}
	}`

**Comment by HaoyCn** [comment]
I don't really think it's better to use variables. In your case, you can simple do this:

```scss
@import 'iconfont';

.bar {
  &::after {
    content: iconfont-item('foo-twitter');
  }
}
```

That is, the default template has already offered us useful functions to cover most cases.

But after all, you are always free to write your own template. Try the option `cssTemplate`.
